# Generated by Django 6.0.3 on 2026-03-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('Id', models.AutoField(help_text='Campo de identificacion unica autogenerado', primary_key=True, serialize=False)),
                ('NombreUsuario', models.CharField(help_text='Nombre completo', max_length=200)),
                ('ApellidoUsuario', models.CharField(help_text='Apellidos completo', max_length=200)),
                ('UserName', models.CharField(help_text='Campo de identificacion del usuario unico', max_length=100, unique=True)),
                ('Correo', models.EmailField(blank=True, help_text='Correo electronico', max_length=254)),
                ('FechaRegistro', models.DateTimeField(help_text='Fecha de registro del usuario', verbose_name='fecha registro')),
                ('LastLogin', models.DateTimeField(help_text='Fecha de registro del usuario', verbose_name='Ultima conexion')),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
    ]
