# Generated by Django 6.0.3 on 2026-03-26 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposGastos',
            fields=[
                ('Id', models.AutoField(help_text='Campo de identificacion unica autogenerado', primary_key=True, serialize=False)),
                ('NombreTipoGasto', models.CharField(help_text='Nombre completo', max_length=200)),
                ('FechaRegistro', models.DateTimeField(help_text='Fecha de registro del Tipo', verbose_name='fecha registro')),
            ],
            options={
                'db_table': 'TiposGastos',
            },
        ),
        migrations.CreateModel(
            name='CategoriasGastos',
            fields=[
                ('Id', models.AutoField(help_text='Campo de identificacion unica autogenerado', primary_key=True, serialize=False)),
                ('NombreCategoria', models.CharField(help_text='Nombre completo', max_length=200)),
                ('FechaRegistro', models.DateTimeField(help_text='Fecha de registro de la Categoria', verbose_name='fecha registro')),
                ('Observacion', models.CharField(blank=True, help_text='Alguna observacion sobre la categoria', max_length=200)),
                ('Usuario', models.ForeignKey(db_column='UsuarioId', on_delete=django.db.models.deletion.PROTECT, related_name='categoria_usuario', to='FinTrackApp.usuarios')),
            ],
            options={
                'db_table': 'CategoriasGastos',
            },
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('Id', models.AutoField(help_text='Campo de identificacion unica autogenerado', primary_key=True, serialize=False)),
                ('NombreGasto', models.CharField(help_text='Nombre completo', max_length=200)),
                ('FechaRegistro', models.DateTimeField(help_text='Fecha de registro de la Categoria', verbose_name='fecha registro')),
                ('Observacion', models.CharField(blank=True, help_text='Alguna observacion sobre el gasto', max_length=200)),
                ('Categoria', models.ForeignKey(db_column='CategoriaID', on_delete=django.db.models.deletion.PROTECT, related_name='categoria_gasto_usuario', to='FinTrackApp.categoriasgastos')),
                ('Usuario', models.ForeignKey(db_column='UsuarioId', on_delete=django.db.models.deletion.PROTECT, related_name='gasto_usuario', to='FinTrackApp.usuarios')),
                ('TipoGasto', models.ForeignKey(db_column='TipoId', on_delete=django.db.models.deletion.PROTECT, related_name='tipo_gasto_usuario', to='FinTrackApp.tiposgastos')),
            ],
            options={
                'db_table': 'Gastos',
            },
        ),
    ]
