# Generated by Django 6.0.3 on 2026-03-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0002_tiposgastos_categoriasgastos_gastos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposIngresos',
            fields=[
                ('Id', models.AutoField(help_text='Campo de identificacion unica autogenerado', primary_key=True, serialize=False)),
                ('NombreTipoIngreso', models.CharField(help_text='Nombre completo', max_length=200)),
                ('FechaRegistro', models.DateTimeField(help_text='Fecha de registro del Tipo', verbose_name='fecha registro')),
            ],
            options={
                'db_table': 'TiposIngresos',
            },
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('Id', models.AutoField(help_text='Campo de identificacion unica autogenerado', primary_key=True, serialize=False)),
                ('NombreIngreso', models.CharField(help_text='Nombre completo', max_length=200)),
                ('FechaRegistro', models.DateTimeField(help_text='Fecha de registro de la Categoria', verbose_name='fecha registro')),
                ('Observacion', models.CharField(blank=True, help_text='Alguna observacion sobre el gasto', max_length=200)),
                ('Usuario', models.ForeignKey(db_column='UsuarioId', on_delete=django.db.models.deletion.PROTECT, related_name='ingreso_usuario', to='FinTrackApp.usuarios')),
                ('TipoIngreso', models.ForeignKey(db_column='TipoId', on_delete=django.db.models.deletion.PROTECT, related_name='tipo_ingreso_usuario', to='FinTrackApp.tiposingresos')),
            ],
            options={
                'db_table': 'Ingresos',
            },
        ),
    ]
