# Generated by Django 6.0.3 on 2026-03-27 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0003_tiposingresos_ingresos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionesActivas',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('FechaConexion', models.DateTimeField(help_text='Fecha/hora en que se conecto', verbose_name='Fecha conexion')),
                ('Dispositivo', models.CharField(blank=True, help_text='Dispositivo Conexion', max_length=200)),
                ('IpConexion', models.CharField(blank=True, help_text='Ip desde donde se conecto', max_length=200)),
                ('IdDjangoUser', models.IntegerField(help_text='ID del usuario en la tabla User de Django', verbose_name='ID Usuario Django')),
                ('TokenSesion', models.CharField(db_index=True, help_text='Token para validación de sesión', max_length=300, unique=True)),
                ('FechaExpiracion', models.DateTimeField(db_index=True, help_text='Fecha/hora hasta donde tendrá vigencia la conexión del usuario', verbose_name='Fecha Expiración')),
                ('ConexionActiva', models.BooleanField(default=True)),
                ('Usuario', models.ForeignKey(db_column='UsuarioId', on_delete=django.db.models.deletion.PROTECT, related_name='sesion_activa_usuario', to='FinTrackApp.usuarios')),
            ],
            options={
                'db_table': 'SesionesActivas',
            },
        ),
    ]
