# Generated by Django 6.0.3 on 2026-03-28 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0004_sesionesactivas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediosPagos',
            fields=[
                ('Id', models.AutoField(help_text='Campo de identificacion unica autogenerado', primary_key=True, serialize=False)),
                ('NombreMedioPago', models.CharField(help_text='Nombre completo', max_length=200)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del Medio', verbose_name='fecha registro')),
                ('Observacion', models.CharField(blank=True, help_text='Alguna observacion sobre el medio', max_length=200)),
                ('IsActive', models.BooleanField(default=True)),
                ('FechaActualizacion', models.DateTimeField(help_text='Fecha de Actualizacion', verbose_name='fecha registro')),
                ('Usuario', models.ForeignKey(db_column='UsuarioId', on_delete=django.db.models.deletion.PROTECT, related_name='medio_pago_usuario', to='FinTrackApp.usuarios')),
            ],
            options={
                'db_table': 'MediosPagos',
            },
        ),
        migrations.CreateModel(
            name='MovimientosGastos',
            fields=[
                ('Id', models.AutoField(help_text='Campo de identificacion unica autogenerado', primary_key=True, serialize=False)),
                ('FechaGasto', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del gasto', verbose_name='fecha registro')),
                ('Observacion', models.CharField(blank=True, help_text='Alguna observacion sobre el gasto', max_length=200)),
                ('UrlImg', models.URLField(blank=True, help_text='URL de la imagen en Supabase Storage', max_length=500, null=True)),
                ('Usuario', models.ForeignKey(db_column='UsuarioId', on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_gasto_usuario', to='FinTrackApp.usuarios')),
            ],
            options={
                'db_table': 'MovimientosGastos',
            },
        ),
        migrations.CreateModel(
            name='MovimientosGastosDetalles',
            fields=[
                ('Id', models.AutoField(help_text='Campo de identificacion unica autogenerado', primary_key=True, serialize=False)),
                ('MontoGasto', models.IntegerField()),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del gasto', verbose_name='fecha registro')),
                ('GastoUsuario', models.ForeignKey(db_column='GastoId', on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_gasto_seleccionado', to='FinTrackApp.gastos')),
                ('MovimientoGasto', models.ForeignKey(db_column='MovimientoId', on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_gasto_cabecera_detalle', to='FinTrackApp.movimientosgastos')),
            ],
            options={
                'db_table': 'MovimientosGastosDetalles',
            },
        ),
        migrations.CreateModel(
            name='MovimientosGastosMediosPagos',
            fields=[
                ('Id', models.AutoField(help_text='Campo de identificacion unica autogenerado', primary_key=True, serialize=False)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro de la forma de pago', verbose_name='fecha registro')),
                ('MontoMedioPago', models.IntegerField()),
                ('MedioPago', models.ForeignKey(db_column='MedioPagoId', on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_gasto_medio_pago', to='FinTrackApp.mediospagos')),
                ('MovimientoGasto', models.ForeignKey(db_column='MovimientoId', on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_gasto_cabecera_medio', to='FinTrackApp.movimientosgastos')),
            ],
            options={
                'db_table': 'MovimientosGastosMediosPagos',
            },
        ),
    ]
