# Generated by Django 6.0.3 on 2026-03-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0005_mediospagos_movimientosgastos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposgastos',
            name='Id',
            field=models.IntegerField(help_text='Campo de identificación única, se debe asignar manualmente', primary_key=True, serialize=False),
        ),
    ]
