# Generated by Django 6.0.3 on 2026-03-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0006_alter_tiposgastos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposingresos',
            name='Id',
            field=models.IntegerField(help_text='Campo de identificación única, se debe asignar manualmente', primary_key=True, serialize=False),
        ),
    ]
