# Generated by Django 6.0.3 on 2026-03-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0007_alter_tiposingresos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposgastos',
            name='FechaRegistro',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del Tipo', verbose_name='fecha registro'),
        ),
        migrations.AlterField(
            model_name='tiposingresos',
            name='FechaRegistro',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del Tipo', verbose_name='fecha registro'),
        ),
    ]
