# Generated by Django 6.0.3 on 2026-03-28 02:48
from django.db import migrations

def seed_tipos(apps, schema_editor):
    # Usás apps.get_model en vez de importar directamente
    # Esto es importante porque trabaja con la versión del modelo en ese momento histórico
    TiposGastos = apps.get_model('FinTrackApp', 'TiposGastos')
    TiposIngresos = apps.get_model('FinTrackApp', 'TiposIngresos')

    TiposGastos.objects.get_or_create(Id=1, defaults={'NombreTipoGasto': 'Fijo'})
    TiposGastos.objects.get_or_create(Id=2, defaults={'NombreTipoGasto': 'Ocasional'})

    TiposIngresos.objects.get_or_create(Id=1, defaults={'NombreTipoIngreso': 'Fijo'})
    TiposIngresos.objects.get_or_create(Id=2, defaults={'NombreTipoIngreso': 'Ocasional'})

def reverse_seed_tipos(apps, schema_editor):
    # Opcional: qué hacer si se revierte la migración
    TiposGastos = apps.get_model('FinTrackApp', 'TiposGastos')
    TiposIngresos = apps.get_model('FinTrackApp', 'TiposIngresos')

    TiposGastos.objects.filter(Id__in=[1, 2]).delete()
    TiposIngresos.objects.filter(Id__in=[1, 2]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0008_alter_tiposgastos_fecharegistro_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_tipos, reverse_seed_tipos),
    ]
