# Generated by Django 6.0.3 on 2026-03-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0009_seed_tipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriasgastos',
            name='FechaRegistro',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de registro de la Categoria', verbose_name='fecha registro'),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='FechaRegistro',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de registro de la Categoria', verbose_name='fecha registro'),
        ),
    ]
