# Generated by Django 6.0.3 on 2026-04-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0010_alter_categoriasgastos_fecharegistro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediospagos',
            name='FechaActualizacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de Actualizacion', verbose_name='fecha registro'),
        ),
    ]
