# Generated by Django 6.0.3 on 2026-04-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0011_alter_mediospagos_fechaactualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='FechaRegistro',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del Ingreso', verbose_name='fecha registro'),
        ),
    ]
