# Generated by Django 6.0.3 on 2026-04-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0012_alter_ingresos_fecharegistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientosgastos',
            name='ObsImg',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
