# Generated by Django 6.0.3 on 2026-04-03 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0013_movimientosgastos_obsimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientosgastos',
            name='FechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 2, 23, 24, 27, 477667), help_text='Fecha de registro del gasto', verbose_name='fecha registro'),
        ),
        migrations.AlterField(
            model_name='movimientosgastos',
            name='FechaGasto',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del gasto', verbose_name='fecha Operacion'),
        ),
    ]
