# Generated by Django 6.0.3 on 2026-04-03 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0014_movimientosgastos_fecharegistro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosgastos',
            name='FechaGasto',
            field=models.DateField(help_text='Fecha de registro del gasto', verbose_name='fecha Operacion'),
        ),
        migrations.AlterField(
            model_name='movimientosgastos',
            name='FechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 3, 2, 27, 15, 184231, tzinfo=datetime.timezone.utc), help_text='Fecha de registro del gasto', verbose_name='fecha registro'),
        ),
    ]
