# Generated by Django 6.0.3 on 2026-04-03 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0015_alter_movimientosgastos_fechagasto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosgastos',
            name='FechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 2, 23, 47, 17, 82824), help_text='Fecha de registro del gasto', verbose_name='fecha registro'),
        ),
    ]
