# Generated by Django 6.0.3 on 2026-04-03 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0016_alter_movimientosgastos_fecharegistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosgastos',
            name='FechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 3, 2, 49, 25, 357384, tzinfo=datetime.timezone.utc), help_text='Fecha de registro del gasto', verbose_name='fecha registro'),
        ),
    ]
