# Generated by Django 6.0.3 on 2026-04-03 02:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0017_alter_movimientosgastos_fecharegistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosgastos',
            name='FechaRegistro',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de registro del gasto', verbose_name='fecha registro'),
        ),
    ]
