# Generated by Django 6.0.3 on 2026-04-03 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0018_alter_movimientosgastos_fecharegistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientosIngresos',
            fields=[
                ('Id', models.AutoField(help_text='Campo de identificacion unica autogenerado', primary_key=True, serialize=False)),
                ('FechaIngreso', models.DateField(help_text='Fecha de registro del ingreso', verbose_name='fecha Operacion')),
                ('Observacion', models.CharField(blank=True, help_text='Alguna observacion sobre el ingreso', max_length=200)),
                ('UrlImg', models.URLField(blank=True, help_text='URL de la imagen en Supabase Storage', max_length=500, null=True)),
                ('ObsImg', models.CharField(blank=True, max_length=500, null=True)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del ingreso', verbose_name='fecha registro')),
                ('Usuario', models.ForeignKey(db_column='UsuarioId', on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_ingreso_usuario', to='FinTrackApp.usuarios')),
            ],
            options={
                'db_table': 'MovimientosIngresos',
            },
        ),
        migrations.CreateModel(
            name='MovimientosIngresosDetalles',
            fields=[
                ('Id', models.AutoField(help_text='Campo de identificacion unica autogenerado', primary_key=True, serialize=False)),
                ('MontoIngreso', models.IntegerField()),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del gasto', verbose_name='fecha registro')),
                ('IngresoUsuario', models.ForeignKey(db_column='IngresoId', on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_ingreso_seleccionado', to='FinTrackApp.ingresos')),
                ('MovimientoIngreso', models.ForeignKey(db_column='MovimientoId', on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_ingreso_cabecera_detalle', to='FinTrackApp.movimientosingresos')),
            ],
            options={
                'db_table': 'MovimientosIngresosDetalles',
            },
        ),
    ]
