# Generated by Django 6.0.3 on 2026-04-15 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0019_movimientosingresos_movimientosingresosdetalles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('Id', models.AutoField(help_text='Campo de identificacion unica autogenerado', primary_key=True, serialize=False)),
                ('NombreEmpresa', models.CharField(blank=True, help_text='Alguna observacion sobre la empresa', max_length=200)),
                ('Ruc', models.CharField(blank=True, help_text='RUC de la empresa', max_length=50)),
                ('UrlImg', models.ImageField(blank=True, help_text='Logo de la empresa', null=True, upload_to='Empresas/')),
                ('ObsImg', models.CharField(blank=True, help_text='Descripción de la imagen', max_length=500, null=True)),
                ('FechaRegistro', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de registro de la empresa', verbose_name='fecha registro')),
            ],
            options={
                'db_table': 'Empresas',
            },
        ),
    ]
