# Generated by Django 6.0.3 on 2026-04-15 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0020_empresas'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientosgastos',
            name='Empresa',
            field=models.ForeignKey(db_column='EmpresaId', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_gasto_empresa', to='FinTrackApp.empresas'),
        ),
    ]
