# Generated by Django 6.0.3 on 2026-04-16 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0021_movimientosgastos_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='ObsImg',
        ),
    ]
