# Generated by Django 6.0.3 on 2026-04-29 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0022_remove_empresas_obsimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientosingresos',
            name='IngresoUsuario',
            field=models.ForeignKey(db_column='IngresoId', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_ingreso_seleccionado', to='FinTrackApp.ingresos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientosingresos',
            name='MontoIngreso',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MovimientosIngresosDetalles',
        ),
    ]
