# Generated by Django 6.0.3 on 2026-04-29 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0023_movimientosingresos_ingresousuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientosingresos',
            name='Empresa',
            field=models.ForeignKey(db_column='EmpresaId', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_ingreso_empresa', to='FinTrackApp.empresas'),
        ),
    ]
