# Generated by Django 6.0.3 on 2026-05-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0024_movimientosingresos_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosgastos',
            name='UrlImg',
            field=models.URLField(blank=True, help_text='URL de la imagen en Cloudflare R2 Storage', max_length=500, null=True),
        ),
    ]
