# Generated by Django 6.0.3 on 2026-05-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTrackApp', '0025_alter_movimientosgastos_urlimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='NombreEmpresa',
            field=models.CharField(blank=True, help_text='Nombre de la empresa', max_length=200),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='UrlImg',
            field=models.URLField(blank=True, help_text='URL del logo en Cloudflare R2 Storage', max_length=500, null=True),
        ),
    ]
